
import React, { useState, useRef, useEffect } from 'react';
import { Model, ServerProfile } from '../types';
import { Send, Bot, User, Cpu, Zap, Eraser, MessageSquare, Power, Loader2, CircleCheck, CircleAlert, Server } from 'lucide-react';

interface ChatProps {
    models: Model[];
    servers: ServerProfile[];
    onUpdateServer: (server: ServerProfile) => void;
}

interface Message {
    id: string;
    role: 'user' | 'assistant';
    content: string;
    timestamp: Date;
}

export const Chat: React.FC<ChatProps> = ({ models, servers, onUpdateServer }) => {
    const [selectedServerId, setSelectedServerId] = useState<string>(servers[0]?.id || '');
    const [messages, setMessages] = useState<Message[]>([
        { id: '1', role: 'assistant', content: 'System initialized. Connect to a server to begin.', timestamp: new Date() }
    ]);
    const [input, setInput] = useState('');
    const [isTyping, setIsTyping] = useState(false);
    const messagesEndRef = useRef<HTMLDivElement>(null);

    const selectedServer = servers.find(s => s.id === selectedServerId) || servers[0];

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    };

    useEffect(() => {
        scrollToBottom();
    }, [messages, isTyping]);

    const handleLaunch = () => {
        if (!selectedServer) return;
        // Optimistic update for launching simulation
        onUpdateServer({ ...selectedServer, status: 'Starting' });
        
        setTimeout(() => {
            onUpdateServer({ ...selectedServer, status: 'Online' });
            setMessages(prev => [...prev, {
                id: Date.now().toString(),
                role: 'assistant',
                content: `Server ${selectedServer.name} is now Online and ready for inference.`,
                timestamp: new Date()
            }]);
        }, 2500);
    };

    const handleSend = () => {
        if (!input.trim()) return;
        if (selectedServer?.status !== 'Online') {
            setMessages(prev => [...prev, {
                id: Date.now().toString(),
                role: 'assistant',
                content: `Error: Cannot send message. Server "${selectedServer?.name || 'Unknown'}" is not Online.`,
                timestamp: new Date()
            }]);
            return;
        }

        const userMsg: Message = {
            id: Date.now().toString(),
            role: 'user',
            content: input,
            timestamp: new Date()
        };

        setMessages(prev => [...prev, userMsg]);
        setInput('');
        setIsTyping(true);

        // Simulate inference delay
        setTimeout(() => {
            const aiMsg: Message = {
                id: (Date.now() + 1).toString(),
                role: 'assistant',
                content: `[${selectedServer.acceleration} Inference via ${selectedServer.name}] This is a simulated response. In a production environment, this would be generated by the endpoint ${selectedServer.host}:${selectedServer.port}.`,
                timestamp: new Date()
            };
            setMessages(prev => [...prev, aiMsg]);
            setIsTyping(false);
        }, 1200);
    };

    return (
        <div className="flex flex-col h-full gap-4 animate-fade-in">
            {/* Header / Toolbar */}
            <div className="flex justify-between items-center bg-nebula-900 border border-nebula-700 p-4 rounded-xl shadow-md">
                <div className="flex items-center gap-4">
                    <div className="flex items-center gap-3">
                        <div className={`p-2 rounded-lg border ${selectedServer?.status === 'Online' ? 'bg-green-900/20 border-green-500/30 text-green-400' : 'bg-nebula-800 border-nebula-700 text-gray-400'}`}>
                            <Bot size={20} />
                        </div>
                        
                        <div className="flex flex-col">
                            <label className="text-[10px] text-gray-500 uppercase font-bold">Target Server</label>
                            <select 
                                value={selectedServerId}
                                onChange={(e) => setSelectedServerId(e.target.value)}
                                className="bg-transparent text-white font-medium text-sm outline-none cursor-pointer hover:text-purple-300 transition-colors"
                            >
                                {servers.map(s => <option key={s.id} value={s.id} className="bg-nebula-900 text-white">{s.name}</option>)}
                            </select>
                        </div>
                    </div>

                    <div className="h-8 w-px bg-nebula-800 mx-2"></div>

                    {/* Server Status & Actions */}
                    <div className="flex items-center gap-4">
                        {selectedServer?.status === 'Online' ? (
                            <div className="flex items-center gap-2 px-3 py-1 bg-green-900/20 border border-green-500/30 rounded-full text-green-400 text-xs font-bold">
                                <CircleCheck size={14} /> Connected
                            </div>
                        ) : selectedServer?.status === 'Starting' ? (
                             <div className="flex items-center gap-2 px-3 py-1 bg-yellow-900/20 border border-yellow-500/30 rounded-full text-yellow-400 text-xs font-bold">
                                <Loader2 size={14} className="animate-spin" /> Booting...
                            </div>
                        ) : (
                             <div className="flex items-center gap-2 px-3 py-1 bg-nebula-800 border border-nebula-700 rounded-full text-gray-500 text-xs font-bold">
                                <CircleAlert size={14} /> Offline
                            </div>
                        )}

                        {selectedServer?.status === 'Offline' && (
                            <button 
                                onClick={handleLaunch}
                                className="px-3 py-1.5 bg-purple-600 hover:bg-purple-500 text-white rounded text-xs font-bold flex items-center gap-2 transition-all shadow-[0_0_10px_rgba(139,92,246,0.3)]"
                            >
                                <Power size={12} /> Launch Server
                            </button>
                        )}
                    </div>
                </div>

                <div className="flex items-center gap-4">
                     <div className="flex bg-nebula-950 rounded-lg p-1 border border-nebula-800">
                        <div className={`flex items-center gap-2 px-3 py-1 rounded text-xs font-bold transition-all ${selectedServer?.acceleration !== 'CPU' ? 'bg-purple-900/40 text-purple-300' : 'text-gray-600'}`}>
                            <Zap size={12} /> GPU
                        </div>
                        <div className={`flex items-center gap-2 px-3 py-1 rounded text-xs font-bold transition-all ${selectedServer?.acceleration === 'CPU' ? 'bg-blue-900/40 text-blue-300' : 'text-gray-600'}`}>
                            <Cpu size={12} /> CPU
                        </div>
                    </div>
                    <button 
                        onClick={() => setMessages([])}
                        className="p-2 text-gray-500 hover:text-red-400 hover:bg-nebula-950 rounded transition-colors"
                        title="Clear Chat"
                    >
                        <Eraser size={18} />
                    </button>
                </div>
            </div>

            {/* Chat Area */}
            <div className="flex-1 bg-nebula-950/50 border border-nebula-800 rounded-xl p-6 overflow-y-auto relative">
                {messages.length === 0 && (
                     <div className="absolute inset-0 flex flex-col items-center justify-center text-gray-600 opacity-50 pointer-events-none">
                        <Server size={64} className="mb-4" />
                        <p>Select a server from the dropdown above to begin</p>
                    </div>
                )}
                <div className="space-y-6">
                    {messages.map((msg) => (
                        <div key={msg.id} className={`flex gap-4 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}>
                            <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${msg.role === 'user' ? 'bg-blue-600' : 'bg-purple-600'}`}>
                                {msg.role === 'user' ? <User size={16} /> : <Bot size={16} />}
                            </div>
                            <div className={`max-w-[70%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${
                                msg.role === 'user' 
                                ? 'bg-blue-900/30 border border-blue-500/30 text-blue-100 rounded-tr-none' 
                                : 'bg-nebula-900 border border-nebula-700 text-gray-200 rounded-tl-none'
                            }`}>
                                {msg.content}
                                <div className="text-[10px] opacity-40 mt-1 text-right">
                                    {msg.timestamp.toLocaleTimeString()}
                                </div>
                            </div>
                        </div>
                    ))}
                    {isTyping && (
                         <div className="flex gap-4">
                            <div className="w-8 h-8 rounded-full bg-purple-600 flex items-center justify-center shrink-0">
                                <Bot size={16} />
                            </div>
                            <div className="bg-nebula-900 border border-nebula-700 rounded-2xl rounded-tl-none px-4 py-3 flex items-center gap-1">
                                <span className="w-1.5 h-1.5 bg-gray-500 rounded-full animate-bounce"></span>
                                <span className="w-1.5 h-1.5 bg-gray-500 rounded-full animate-bounce delay-75"></span>
                                <span className="w-1.5 h-1.5 bg-gray-500 rounded-full animate-bounce delay-150"></span>
                            </div>
                        </div>
                    )}
                    <div ref={messagesEndRef} />
                </div>
            </div>

            {/* Input Area */}
            <div className="bg-nebula-900 border border-nebula-700 rounded-xl p-2 flex items-center gap-2">
                <input 
                    type="text" 
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleSend()}
                    placeholder={selectedServer?.status === 'Online' ? "Type your message..." : "Server is offline..."}
                    disabled={selectedServer?.status !== 'Online'}
                    className="flex-1 bg-transparent border-none outline-none text-white px-4 py-2 disabled:opacity-50 disabled:cursor-not-allowed"
                />
                <button 
                    onClick={handleSend}
                    disabled={!input.trim() || isTyping || selectedServer?.status !== 'Online'}
                    className="p-3 bg-purple-600 hover:bg-purple-500 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-lg transition-colors"
                >
                    <Send size={18} />
                </button>
            </div>
        </div>
    );
};
